name: WallpaperWorld
description: Make Change On your Screen
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.2
  share: ^0.6.5+4
  dio: ^3.0.10
  bottom_navy_bar: ^5.6.0
  url_launcher: ^5.4.10
  cached_network_image:
#   wallpaper_manager: ^1.0.10
  permission_handler: ^5.0.1+1
  data_connection_checker: ^0.3.4
  wallpaperplugin: ^0.1.1
#   permission_handler: ^4.2.0+hotfix.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - image/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-SemiBold.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "image/ic_launcher.png"
